/**
 * Mock Actions, Subtasks, Evidences, Comments, History, Risks
 */

import { mockStore } from './mockData'

// ============================================================
// AÇÕES (50+ ações em vários status)
// ============================================================

mockStore.actions = [
  // ========== RH 2026 — 42 ações reais (seed CSV v1) ==========
  // --- Programa CONECTA (12 ações) ---
  { id: 'RH-CON-01', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C1.1 — Log de decisões: definir critério + template + repositório', description: 'Definir o que é "decisão relevante", publicar template padrão e repositório oficial do log de decisões.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-06', due_date: '2026-02-20', completed_at: null, progress: 0, evidence_required: true, notes: 'Template publicado + link repositório + relatório de aderência (mês 1)', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-02', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C1.1 — Log de decisões: SLA e rotina (piloto 30 dias)', description: 'Rodar piloto de 30 dias com SLA (ex.: publicar em 48h) e ajustar formato.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-21', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'SLA documentado + relatório mensal (decisões esperadas vs registradas)', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-03', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C2.1 — Fala AERO: pauta fixa + calendário anual', description: 'Definir pauta fixa, calendário e responsáveis por seção para o boletim institucional.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-06', due_date: '2026-02-28', completed_at: null, progress: 0, evidence_required: true, notes: 'Calendário anual + pauta fixa + responsáveis por seção', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-04', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C2.1 — Fala AERO: Edição Q1', description: 'Produzir e publicar as edições do Q1 e consolidar padrão.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Edição publicada + checklist pauta fixa preenchido', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-05', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C2.1 — Fala AERO: Edição Q2', description: 'Executar cadência mensal no Q2 e manter histórico.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Edições publicadas (abr/mai/jun) + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-06', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C2.1 — Fala AERO: Edição Q3', description: 'Executar cadência mensal no Q3 e manter histórico.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-07-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Edições publicadas (jul/ago/set) + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-07', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C2.1 — Fala AERO: Edição Q4', description: 'Executar cadência mensal no Q4 e consolidar histórico.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-10-01', due_date: '2026-12-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Edições publicadas (out/nov/dez) + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-08', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C3.1 — Interáreas: ritual + backlog de dependências', description: 'Definir pauta padrão e backlog único de dependências (com dono e prazo).', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-10', due_date: '2026-03-10', completed_at: null, progress: 0, evidence_required: true, notes: 'Template de ata + backlog criado (com donos e prazos)', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-09', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C3.1 — Interáreas: Ciclo 1', description: 'Rodar 2 encontros e medir % ações concluídas.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-11', due_date: '2026-05-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Atas + backlog com status + % concluído', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-10', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C3.1 — Interáreas: Ciclo 2', description: 'Rodar 2 encontros e medir % ações concluídas.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-06-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Atas + backlog com status + % concluído', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-11', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C3.1 — Interáreas: Ciclo 3', description: 'Rodar 2 encontros e medir % ações concluídas (encerramento anual).', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-10-01', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: 'Atas + backlog com status + % concluído', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-CON-12', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'conecta', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'C4.1 — Canal de escuta com devolutiva (SLA)', description: 'Implantar canal com triagem semanal e SLA de devolutiva; registrar entradas/destino/retorno.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-15', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Canal ativo + log mensal + SLA reportado', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  // --- Programa DESENVOLVE (14 ações) ---
  { id: 'RH-DES-01', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D2.1 — Checklist 4/4: padrão + baseline Q1', description: 'Definir checklist 4/4, ferramenta de registro e medir baseline no Q1.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-06', due_date: '2026-03-15', completed_at: null, progress: 0, evidence_required: true, notes: 'Checklist publicado + baseline Q1 + indicador mensal por área', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-02', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D2.1 — Aderência rituais: plano de correção', description: 'Criar plano de correção para áreas/líderes abaixo do mínimo.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-16', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Plano de correção + evolução mensal', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-03', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D1.1 — Escola de Líderes: trilhas + calendário anual', description: 'Publicar trilhas por nível e calendário anual.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-10', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Calendário anual + lista líderes + presença 1º módulo', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-04', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D1.1 — Escola de Líderes: Execução Q2', description: 'Executar módulos do Q2 e avaliar (NPS por ciclo).', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Presenças + NPS/ciclo + log de ajustes', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-05', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D1.1 — Escola de Líderes: Execução Q3', description: 'Executar módulos do Q3 e avaliar.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-07-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Presenças + NPS/ciclo + registro de casos', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-06', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O2', section_id: null, node_type: 'acao', title: 'D1.1 — Escola de Líderes: Execução Q4', description: 'Executar módulos do Q4 e consolidar lições aprendidas.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-10-01', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: 'Presenças + NPS/ciclo + relatório anual curto', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-07', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'D3.1 — Metas+competências: framework + comunicação', description: 'Definir framework de metas + competências e comunicar ciclo anual.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-15', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Framework + comunicado oficial + metas por área (v1)', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-08', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'D3.1 — Metas por área: revisão executiva v2', description: 'Revisar metas por área com Direção e travar v2 com registro.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-04-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Metas v2 + ata de revisão', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-09', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'Avaliação: ciclo principal (≥95%)', description: 'Executar ciclo principal e atingir ≥95% avaliações concluídas.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-06-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Relatório % concluído por área + pendências', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-10', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'Nine Box: preparar critérios + calendário', description: 'Preparar sessões de calibragem e critérios para Nine Box.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-15', due_date: '2026-05-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Calendário + critérios + lista áreas elegíveis', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-11', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'Nine Box: execução até Jul/2026', description: 'Rodar sessões de calibragem e concluir Nine Box para 100% áreas elegíveis.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-06-01', due_date: '2026-07-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Mapas por área + decisões registradas', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-12', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O1', section_id: null, node_type: 'acao', title: 'Onboarding 45/90: desenho + piloto', description: 'Desenhar trilhas 45/90 e rodar piloto em 2 funções críticas.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-05-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Checklists por função + avaliação 45/90 + buddy', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-13', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O1', section_id: null, node_type: 'acao', title: 'Onboarding 45/90: escala Q3', description: 'Escalar onboarding 45/90 e medir completude.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-06-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: '% completude + avaliações + gaps', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-DES-14', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'desenvolve', objective_key: 'O4', section_id: null, node_type: 'acao', title: 'PDIs: críticos primeiro + revisão trimestral', description: 'Criar PDIs para 100% críticos até Jun e governar revisões trimestrais.', status: 'PENDENTE', priority: 'P1', responsible: 'Líderes | RH', assigned_to: null, start_date: '2026-03-15', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: 'PDIs ativos + % revisões no prazo + evidências', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  // --- Programa RECONHECE (8 ações) ---
  { id: 'RH-REC-01', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Guia de critérios do reconhecimento', description: 'Criar guia de critérios, exemplos e revisão semestral.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-10', due_date: '2026-03-10', completed_at: null, progress: 0, evidence_required: true, notes: 'Guia publicado + versionamento + uso no ciclo', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-02', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Reconhecer é AERO: setup + ciclo 1', description: 'Definir rito mensal, critérios e executar 1º ciclo.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Registro do ciclo + comunicado', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-03', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Reconhecer é AERO: ciclos Q2', description: 'Executar ciclos mensais do Q2 e manter histórico.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Registros mensais Q2 + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-04', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Reconhecer é AERO: ciclos Q3', description: 'Executar ciclos mensais do Q3.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-07-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: 'Registros mensais Q3 + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-05', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Reconhecer é AERO: ciclos Q4', description: 'Executar ciclos mensais do Q4 e consolidar aprendizados.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-10-01', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: 'Registros mensais Q4 + histórico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-06', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Líder como agente: aderência ≥90%', description: 'Garantir participação mínima mensal de líderes e medir aderência.', status: 'PENDENTE', priority: 'P1', responsible: 'Líderes | RH', assigned_to: null, start_date: '2026-03-15', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: '% líderes participantes mensalmente + registro simples', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-07', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O3', section_id: null, node_type: 'acao', title: 'Pulso trimestral de reconhecimento (4 ciclos)', description: 'Aplicar pulso trimestral e gerar plano por ciclo.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-31', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: 'Resultados do pulso + plano por ciclo + execução', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-REC-08', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'reconhece', objective_key: 'O1', section_id: null, node_type: 'acao', title: 'Correlação reconhecimento x turnover críticos', description: 'Analisar trimestralmente correlação e propor ações corretivas.', status: 'PENDENTE', priority: 'P2', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-12-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Relatório trimestral + decisões no MBR', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  // --- Programa INOVA (8 ações) ---
  { id: 'RH-INO-01', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O1', section_id: null, node_type: 'acao', title: 'CRIT-01 — Posições críticas + risco de saída', description: 'Formalizar lista de críticos e critérios de risco; revisão mensal no MBR.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-06', due_date: '2026-03-15', completed_at: null, progress: 0, evidence_required: true, notes: 'CRIT-01 publicado + plano de retenção por crítico', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-02', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O1', section_id: null, node_type: 'acao', title: 'LEAD-01 — Líderes elegíveis (v1)', description: 'Formalizar lista de líderes elegíveis e níveis para escola/rituais.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-06', due_date: '2026-02-28', completed_at: null, progress: 0, evidence_required: true, notes: 'LEAD-01 publicado + baseline elegíveis', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-03', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'Dicionário de KPIs (fonte única)', description: 'Definir KPIs oficiais com fórmula, fonte, dono, cadência e gatilho.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-02-15', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Documento versionado + validação no MBR', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-04', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'Painel RH 1.0 (SLA mensal)', description: 'Implantar painel mínimo e rotina de snapshot mensal.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-05-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Link painel + log atualização + snapshot mensal', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-05', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'MBR RH mensal (ata + backlog)', description: 'Instalar MBR mensal com ata, backlog e % execução no prazo.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: '12 atas + backlog + % execução no prazo', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-06', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'GPTW: Plano anual v1 + owners por gap', description: 'Publicar plano anual GPTW com gaps priorizados, owners e evidências.', status: 'PENDENTE', priority: 'P0', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-01', due_date: '2026-03-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Plano + owners + checklist readiness v1', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-07', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'GPTW readiness trimestral (4 ciclos)', description: 'Executar checklists trimestrais e anexar evidências por gap.', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-04-01', due_date: '2026-12-15', completed_at: null, progress: 0, evidence_required: true, notes: '4 checklists + evidências por gap + evolução', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },
  { id: 'RH-INO-08', plan_id: 'plan-rh-2026', pillar_id: null, area_okr_id: null, initiative_id: null, parent_action_id: null, pack_id: 'pack-rh-2026', program_key: 'inova', objective_key: 'O5', section_id: null, node_type: 'acao', title: 'Fechamento mensal RH (MD+PDF) como evidência', description: 'Gerar fechamento mensal e salvar como evidência auditável (MD + PDF).', status: 'PENDENTE', priority: 'P1', responsible: 'Renata Silvestre | Fernanda Xavier', assigned_to: null, start_date: '2026-03-31', due_date: '2026-12-31', completed_at: null, progress: 0, evidence_required: true, notes: 'Arquivo MD + PDF mensal + link registrado no pack', cost_estimate: null, cost_actual: null, cost_type: null, currency: 'BRL', created_at: '2026-02-06T00:00:00Z', updated_at: '2026-02-06T00:00:00Z' },

  // ========== MARKETING 2026 (20 acoes) ==========
  { id: 'MKT-INB-01', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'Lancar campanha de inbound marketing', description: 'Estruturar funil de conteudo e automacao', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-01-10', due_date: '2026-03-31', completed_at: null, progress: 60, evidence_required: true, notes: 'Funil estruturado, iniciando automacoes', cost_estimate: 120000, cost_actual: 72000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-10T00:00:00Z', updated_at: '2026-02-15T00:00:00Z' },
  { id: 'MKT-BRD-01', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Redesenhar identidade visual', description: 'Atualizar brand book e guidelines', status: 'EM_VALIDACAO', priority: 'P1', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-02-01', due_date: '2026-04-30', completed_at: null, progress: 90, evidence_required: true, notes: 'Em validacao com diretoria', cost_estimate: 85000, cost_actual: 82000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-25T00:00:00Z' },
  { id: 'MKT-ABM-01', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'abm', objective_key: 'M3', section_id: null, node_type: 'acao', title: 'Implementar ABM para enterprise', description: 'Account-based marketing para top 50 contas', status: 'PENDENTE', priority: 'P1', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-04-01', due_date: '2026-08-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 200000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-BRD-02', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Lancar novo site institucional', description: 'Redesign completo do site corporativo', status: 'CONCLUIDA', priority: 'P0', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-01-05', due_date: '2026-02-28', completed_at: '2026-02-20T00:00:00Z', progress: 100, evidence_required: true, notes: 'Site lancado com sucesso', cost_estimate: 150000, cost_actual: 145000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-02-20T00:00:00Z' },
  { id: 'MKT-INB-02', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'Criar calendario editorial Q1/Q2', description: 'Planejar conteudo para 6 meses', status: 'CONCLUIDA', priority: 'P0', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-01-05', due_date: '2026-01-31', completed_at: '2026-01-28T00:00:00Z', progress: 100, evidence_required: true, notes: 'Calendario aprovado', cost_estimate: 5000, cost_actual: 5000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-01-28T00:00:00Z' },
  { id: 'MKT-INB-03', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'Configurar automacao de email marketing', description: 'Setup HubSpot workflows e nurturing', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-02-01', due_date: '2026-04-30', completed_at: null, progress: 45, evidence_required: true, notes: 'Workflows basicos prontos', cost_estimate: 30000, cost_actual: 15000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'MKT-INB-04', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'Produzir 12 whitepapers tematicos', description: 'Conteudo rico para geracao de leads', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-02-01', due_date: '2026-07-31', completed_at: null, progress: 25, evidence_required: true, notes: '3 de 12 publicados', cost_estimate: 60000, cost_actual: 15000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'MKT-INB-05', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M4', section_id: null, node_type: 'acao', title: 'Otimizar landing pages (CRO)', description: 'Testes A/B e otimizacao de conversao', status: 'PENDENTE', priority: 'P2', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-03-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 20000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-BRD-03', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Campanha institucional Q1', description: 'Branding awareness multicanal', status: 'CONCLUIDA', priority: 'P1', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-01-15', due_date: '2026-03-31', completed_at: '2026-03-28T00:00:00Z', progress: 100, evidence_required: true, notes: 'Campanha veiculada com sucesso', cost_estimate: 80000, cost_actual: 78000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-28T00:00:00Z' },
  { id: 'MKT-BRD-04', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Campanha institucional Q2', description: 'Branding awareness multicanal', status: 'PENDENTE', priority: 'P1', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-04-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 80000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-ABM-02', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'abm', objective_key: 'M3', section_id: null, node_type: 'acao', title: 'Mapear top 50 contas enterprise', description: 'ICP e scoring de contas-alvo', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-02-15', due_date: '2026-03-31', completed_at: null, progress: 70, evidence_required: true, notes: '35 contas mapeadas', cost_estimate: 15000, cost_actual: 10000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-15T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'MKT-ABM-03', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'abm', objective_key: 'M3', section_id: null, node_type: 'acao', title: 'Criar playbooks ABM por segmento', description: 'Playbooks personalizados por verticais', status: 'PENDENTE', priority: 'P2', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-04-01', due_date: '2026-06-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 25000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-INB-06', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'Implementar lead scoring', description: 'Modelo preditivo de qualificacao de leads', status: 'PENDENTE', priority: 'P1', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-03-15', due_date: '2026-05-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 40000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-BRD-05', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Pesquisa de brand awareness H1', description: 'Medir awareness antes e depois das campanhas', status: 'PENDENTE', priority: 'P2', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-06-01', due_date: '2026-07-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 35000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-INB-07', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M4', section_id: null, node_type: 'acao', title: 'Dashboard de performance marketing', description: 'Painel consolidado de metricas de marketing', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-02-01', due_date: '2026-03-31', completed_at: null, progress: 80, evidence_required: true, notes: 'Dashboard 80% pronto', cost_estimate: 25000, cost_actual: 20000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'MKT-INB-08', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M1', section_id: null, node_type: 'acao', title: 'SEO: auditoria e plano de otimizacao', description: 'Auditoria tecnica e plano de conteudo SEO', status: 'CONCLUIDA', priority: 'P1', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-01-10', due_date: '2026-02-28', completed_at: '2026-02-25T00:00:00Z', progress: 100, evidence_required: true, notes: 'Auditoria completa, plano aprovado', cost_estimate: 15000, cost_actual: 14000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-10T00:00:00Z', updated_at: '2026-02-25T00:00:00Z' },
  { id: 'MKT-BRD-06', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Programa de embaixadores de marca', description: 'Employee advocacy e influenciadores internos', status: 'PENDENTE', priority: 'P2', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-05-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 20000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-ABM-04', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'abm', objective_key: 'M3', section_id: null, node_type: 'acao', title: 'Eventos exclusivos para contas-chave', description: 'Executive dinners e roundtables', status: 'PENDENTE', priority: 'P2', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-05-01', due_date: '2026-10-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 100000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'MKT-INB-09', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-mkt-1', initiative_id: 'init-7', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'inbound', objective_key: 'M4', section_id: null, node_type: 'acao', title: 'Revisao e otimizacao CAC trimestral', description: 'Analise e reducao do custo de aquisicao', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Carlos Silva', assigned_to: 'user-2', start_date: '2026-01-15', due_date: '2026-12-31', completed_at: null, progress: 30, evidence_required: true, notes: 'Q1 analisado, CAC caiu 8%', cost_estimate: 10000, cost_actual: 3000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-31T00:00:00Z' },
  { id: 'MKT-BRD-07', plan_id: 'plan-mkt-2026', pillar_id: 'pillar-5', area_okr_id: 'area-okr-mkt-2', initiative_id: 'init-8', parent_action_id: null, pack_id: 'pack-mkt-2026', program_key: 'brand', objective_key: 'M2', section_id: null, node_type: 'acao', title: 'Gestao de redes sociais (12 meses)', description: 'Calendario e publicacao em redes', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Fernanda Costa', assigned_to: 'user-8', start_date: '2026-01-01', due_date: '2026-12-31', completed_at: null, progress: 20, evidence_required: true, notes: 'Jan/Fev publicados', cost_estimate: 48000, cost_actual: 8000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-28T00:00:00Z' },

  // ========== OPERACOES 2026 (20 acoes) ==========
  { id: 'OPS-RPA-01', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP2', section_id: null, node_type: 'acao', title: 'Implementar RPA em processos de compras', description: 'Automatizar 15 processos de purchasing', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-01-20', due_date: '2026-05-31', completed_at: null, progress: 55, evidence_required: true, notes: '8 processos ja automatizados', cost_estimate: 180000, cost_actual: 95000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-03-01T00:00:00Z' },
  { id: 'OPS-LEA-01', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP3', section_id: null, node_type: 'acao', title: 'Certificacao Lean Six Sigma Green Belt', description: 'Formar 20 colaboradores em Green Belt', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-02-15', due_date: '2026-06-30', completed_at: null, progress: 40, evidence_required: true, notes: 'Turma 1 em andamento', cost_estimate: 100000, cost_actual: 40000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-15T00:00:00Z', updated_at: '2026-03-10T00:00:00Z' },
  { id: 'OPS-RPA-02', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP1', section_id: null, node_type: 'acao', title: 'Mapear e otimizar cadeia de suprimentos', description: 'Value stream mapping completo', status: 'CONCLUIDA', priority: 'P0', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-01-05', due_date: '2026-02-28', completed_at: '2026-02-20T00:00:00Z', progress: 100, evidence_required: true, notes: 'Mapeamento concluido', cost_estimate: 50000, cost_actual: 45000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-02-20T00:00:00Z' },
  { id: 'OPS-LEA-02', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP4', section_id: null, node_type: 'acao', title: 'Implementar gestao visual', description: 'Deploy de dashboards de producao', status: 'AGUARDANDO_EVIDENCIA', priority: 'P2', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-02-01', due_date: '2026-04-30', completed_at: null, progress: 85, evidence_required: true, notes: 'Dashboards prontos, aguardando evidencias', cost_estimate: 35000, cost_actual: 32000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-25T00:00:00Z' },
  { id: 'OPS-RPA-03', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP2', section_id: null, node_type: 'acao', title: 'RPA em contas a pagar', description: 'Automatizar conciliacao e pagamentos', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-02-01', due_date: '2026-05-31', completed_at: null, progress: 35, evidence_required: true, notes: 'Em desenvolvimento', cost_estimate: 80000, cost_actual: 28000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'OPS-RPA-04', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP2', section_id: null, node_type: 'acao', title: 'RPA em faturamento', description: 'Automatizar emissao de notas fiscais', status: 'PENDENTE', priority: 'P1', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-04-01', due_date: '2026-07-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 60000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'OPS-LEA-03', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP3', section_id: null, node_type: 'acao', title: 'Projeto Kaizen: linha de producao A', description: 'Reducao de desperdicios na linha principal', status: 'CONCLUIDA', priority: 'P0', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-01-10', due_date: '2026-02-28', completed_at: '2026-02-25T00:00:00Z', progress: 100, evidence_required: true, notes: 'Kaizen concluido, -18% desperdicio', cost_estimate: 30000, cost_actual: 28000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-10T00:00:00Z', updated_at: '2026-02-25T00:00:00Z' },
  { id: 'OPS-LEA-04', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP3', section_id: null, node_type: 'acao', title: 'Projeto Kaizen: linha de producao B', description: 'Reducao de desperdicios na segunda linha', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-03-01', due_date: '2026-05-31', completed_at: null, progress: 20, evidence_required: true, notes: 'Mapeamento iniciado', cost_estimate: 30000, cost_actual: 6000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-03-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'OPS-RPA-05', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP1', section_id: null, node_type: 'acao', title: 'Implementar WMS (Warehouse Management)', description: 'Sistema de gestao de armazem', status: 'PENDENTE', priority: 'P1', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-05-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 150000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'OPS-LEA-05', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP3', section_id: null, node_type: 'acao', title: 'Programa 5S em todas as unidades', description: 'Implantacao e auditoria 5S', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-01-15', due_date: '2026-06-30', completed_at: null, progress: 50, evidence_required: true, notes: '3 de 6 unidades concluidas', cost_estimate: 20000, cost_actual: 10000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'OPS-RPA-06', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP2', section_id: null, node_type: 'acao', title: 'Automatizar relatorios operacionais', description: 'Geracao automatica de reports diarios', status: 'CONCLUIDA', priority: 'P1', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-01-15', due_date: '2026-02-28', completed_at: '2026-02-22T00:00:00Z', progress: 100, evidence_required: true, notes: 'Relatorios automatizados', cost_estimate: 20000, cost_actual: 18000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-02-22T00:00:00Z' },
  { id: 'OPS-LEA-06', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP1', section_id: null, node_type: 'acao', title: 'Mapeamento de processos criticos', description: 'BPMN para top 20 processos', status: 'CONCLUIDA', priority: 'P0', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-01-05', due_date: '2026-02-15', completed_at: '2026-02-12T00:00:00Z', progress: 100, evidence_required: true, notes: '20 processos mapeados', cost_estimate: 15000, cost_actual: 14000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-02-12T00:00:00Z' },
  { id: 'OPS-RPA-07', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP2', section_id: null, node_type: 'acao', title: 'RPA em onboarding de fornecedores', description: 'Automatizar cadastro e validacao', status: 'PENDENTE', priority: 'P2', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-06-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 45000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'OPS-LEA-07', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP4', section_id: null, node_type: 'acao', title: 'Painel OPS: KPIs tempo real', description: 'Dashboard operacional com metricas-chave', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-02-01', due_date: '2026-04-30', completed_at: null, progress: 65, evidence_required: true, notes: 'Metricas basicas implementadas', cost_estimate: 40000, cost_actual: 26000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'OPS-RPA-08', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-1', initiative_id: 'init-1', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'rpa', objective_key: 'OP1', section_id: null, node_type: 'acao', title: 'Reducao de lead time logistico', description: 'Otimizar rotas e consolidacao', status: 'PENDENTE', priority: 'P1', responsible: 'Roberto Lima', assigned_to: 'user-3', start_date: '2026-04-01', due_date: '2026-08-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 50000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'OPS-LEA-08', plan_id: 'plan-ops-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-ops-2', initiative_id: 'init-2', parent_action_id: null, pack_id: 'pack-ops-2026', program_key: 'lean', objective_key: 'OP3', section_id: null, node_type: 'acao', title: 'Treinamento Lean para gestores', description: 'Capacitacao de 15 gestores operacionais', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Patricia Almeida', assigned_to: 'user-9', start_date: '2026-02-15', due_date: '2026-05-31', completed_at: null, progress: 30, evidence_required: true, notes: '5 de 15 treinados', cost_estimate: 40000, cost_actual: 12000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-15T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },

  // ========== TI 2026 ==========
  { id: 'action-ti-1', plan_id: 'plan-ti-2026', pillar_id: 'pillar-2', area_okr_id: 'area-okr-ti-1', initiative_id: 'init-3', parent_action_id: null, pack_id: null, program_key: null, objective_key: null, section_id: null, node_type: 'acao', title: 'Migrar ERP para cloud', description: 'Migração do SAP para Azure', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Carlos Mendes', assigned_to: 'user-4', start_date: '2026-01-15', due_date: '2026-09-30', completed_at: null, progress: 35, evidence_required: true, notes: 'Fase de preparação concluída', cost_estimate: 500000, cost_actual: 175000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-01T00:00:00Z' },
  { id: 'action-ti-2', plan_id: 'plan-ti-2026', pillar_id: 'pillar-2', area_okr_id: 'area-okr-ti-2', initiative_id: 'init-4', parent_action_id: null, pack_id: null, program_key: null, objective_key: null, section_id: null, node_type: 'acao', title: 'Implementar Zero Trust Security', description: 'Deploy de arquitetura Zero Trust', status: 'AGUARDANDO_EVIDENCIA', priority: 'P0', responsible: 'Lucas Oliveira', assigned_to: 'user-10', start_date: '2026-02-01', due_date: '2026-06-30', completed_at: null, progress: 75, evidence_required: true, notes: 'Aguardando auditoria', cost_estimate: 250000, cost_actual: 220000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'action-ti-3', plan_id: 'plan-ti-2026', pillar_id: 'pillar-2', area_okr_id: 'area-okr-ti-1', initiative_id: 'init-3', parent_action_id: null, pack_id: null, program_key: null, objective_key: null, section_id: null, node_type: 'acao', title: 'Modernizar infraestrutura de rede', description: 'Upgrade de switches e firewalls', status: 'CONCLUIDA', priority: 'P1', responsible: 'Carlos Mendes', assigned_to: 'user-4', start_date: '2026-01-05', due_date: '2026-03-31', completed_at: '2026-03-15T00:00:00Z', progress: 100, evidence_required: true, notes: 'Infraestrutura atualizada', cost_estimate: 350000, cost_actual: 340000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'action-ti-4', plan_id: 'plan-ti-2026', pillar_id: 'pillar-2', area_okr_id: 'area-okr-ti-2', initiative_id: 'init-4', parent_action_id: null, pack_id: null, program_key: null, objective_key: null, section_id: null, node_type: 'acao', title: 'Implementar SOC 24x7', description: 'Centro de operações de segurança', status: 'PENDENTE', priority: 'P1', responsible: 'Lucas Oliveira', assigned_to: 'user-10', start_date: '2026-07-01', due_date: '2026-12-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 400000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-10T00:00:00Z', updated_at: '2026-01-10T00:00:00Z' },

  // ========== FINANCEIRO 2026 (20 acoes) ==========
  { id: 'FIN-AUT-01', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F1', section_id: null, node_type: 'acao', title: 'Automatizar fechamento contabil', description: 'Reduzir ciclo de 10 para 5 dias', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-02-01', due_date: '2026-07-31', completed_at: null, progress: 40, evidence_required: true, notes: 'Primeira fase concluida', cost_estimate: 120000, cost_actual: 48000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-10T00:00:00Z' },
  { id: 'FIN-COM-01', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: 'init-10', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Implementar sistema de compliance', description: 'Deploy de GRC platform', status: 'CONCLUIDA', priority: 'P0', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2025-10-01', due_date: '2026-01-31', completed_at: '2026-01-28T00:00:00Z', progress: 100, evidence_required: true, notes: 'Sistema em producao', cost_estimate: 200000, cost_actual: 195000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2025-10-01T00:00:00Z', updated_at: '2026-01-28T00:00:00Z' },
  { id: 'FIN-AUT-02', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F3', section_id: null, node_type: 'acao', title: 'Implementar FP&A analytics', description: 'Dashboard de planejamento financeiro', status: 'PENDENTE', priority: 'P1', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-05-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 90000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-COM-02', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Auditoria SOX compliance', description: 'Preparacao para auditoria externa', status: 'EM_VALIDACAO', priority: 'P0', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-01-15', due_date: '2026-03-31', completed_at: null, progress: 95, evidence_required: true, notes: 'Documentacao em revisao final', cost_estimate: 75000, cost_actual: 70000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'FIN-AUT-03', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F1', section_id: null, node_type: 'acao', title: 'Automatizar conciliacao bancaria', description: 'RPA para conciliacao diaria', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-02-15', due_date: '2026-06-30', completed_at: null, progress: 50, evidence_required: true, notes: 'Fase 1 concluida, fase 2 em andamento', cost_estimate: 80000, cost_actual: 40000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-15T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'FIN-COM-03', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: 'init-10', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Treinamento compliance para gestores', description: 'Capacitacao em normas e procedimentos', status: 'CONCLUIDA', priority: 'P1', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-01-10', due_date: '2026-02-28', completed_at: '2026-02-20T00:00:00Z', progress: 100, evidence_required: true, notes: '100% gestores treinados', cost_estimate: 25000, cost_actual: 22000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-10T00:00:00Z', updated_at: '2026-02-20T00:00:00Z' },
  { id: 'FIN-AUT-04', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F1', section_id: null, node_type: 'acao', title: 'Automatizar DRE e balancete', description: 'Geracao automatica de demonstrativos', status: 'PENDENTE', priority: 'P1', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-04-01', due_date: '2026-08-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 60000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-COM-04', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Matriz de riscos atualizada', description: 'Revisao trimestral da matriz de riscos', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-01-15', due_date: '2026-12-31', completed_at: null, progress: 25, evidence_required: true, notes: 'Q1 atualizado', cost_estimate: 15000, cost_actual: 4000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-31T00:00:00Z' },
  { id: 'FIN-AUT-05', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F4', section_id: null, node_type: 'acao', title: 'Dashboard de fluxo de caixa', description: 'Visibilidade em tempo real do cash flow', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-02-01', due_date: '2026-04-30', completed_at: null, progress: 70, evidence_required: true, notes: 'MVP pronto, ajustando integracao', cost_estimate: 45000, cost_actual: 32000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'FIN-COM-05', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: 'init-10', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Politica de controles internos v2', description: 'Atualizar e publicar politica de controles', status: 'CONCLUIDA', priority: 'P1', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-01-05', due_date: '2026-02-15', completed_at: '2026-02-10T00:00:00Z', progress: 100, evidence_required: true, notes: 'Politica publicada e aprovada', cost_estimate: 10000, cost_actual: 8000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-05T00:00:00Z', updated_at: '2026-02-10T00:00:00Z' },
  { id: 'FIN-AUT-06', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F3', section_id: null, node_type: 'acao', title: 'Modelo de forecast preditivo', description: 'ML para previsao de receita e despesas', status: 'PENDENTE', priority: 'P2', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-06-01', due_date: '2026-10-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 100000, cost_actual: 0, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-COM-06', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Auditoria interna Q1', description: 'Ciclo de auditoria interna trimestral', status: 'CONCLUIDA', priority: 'P0', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-01-15', due_date: '2026-03-15', completed_at: '2026-03-10T00:00:00Z', progress: 100, evidence_required: true, notes: 'Zero achados criticos', cost_estimate: 30000, cost_actual: 28000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-10T00:00:00Z' },
  { id: 'FIN-AUT-07', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F1', section_id: null, node_type: 'acao', title: 'Integracao ERP-Banco automatizada', description: 'API para conciliacao automatica', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-03-01', due_date: '2026-06-30', completed_at: null, progress: 30, evidence_required: true, notes: 'API em desenvolvimento', cost_estimate: 50000, cost_actual: 15000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-03-01T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'FIN-COM-07', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Auditoria interna Q2', description: 'Ciclo de auditoria interna trimestral', status: 'PENDENTE', priority: 'P0', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-04-01', due_date: '2026-06-15', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 30000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-AUT-08', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F4', section_id: null, node_type: 'acao', title: 'Otimizar gestao de capital de giro', description: 'Reduzir ciclo financeiro em 10 dias', status: 'PENDENTE', priority: 'P1', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-04-01', due_date: '2026-09-30', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 30000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-COM-08', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: 'init-10', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Sistema de denuncias anonimas', description: 'Canal etico com rastreabilidade', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-02-01', due_date: '2026-05-31', completed_at: null, progress: 60, evidence_required: true, notes: 'Plataforma contratada, em configuracao', cost_estimate: 40000, cost_actual: 24000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-02-01T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
  { id: 'FIN-AUT-09', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F3', section_id: null, node_type: 'acao', title: 'Relatorio gerencial automatizado', description: 'Geracao mensal automatica para diretoria', status: 'EM_ANDAMENTO', priority: 'P1', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-02-15', due_date: '2026-05-31', completed_at: null, progress: 45, evidence_required: true, notes: 'Template definido, integrando dados', cost_estimate: 25000, cost_actual: 12000, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-02-15T00:00:00Z', updated_at: '2026-03-20T00:00:00Z' },
  { id: 'FIN-COM-09', plan_id: 'plan-fin-2026', pillar_id: 'pillar-4', area_okr_id: 'area-okr-fin-2', initiative_id: null, parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'compliance', objective_key: 'F2', section_id: null, node_type: 'acao', title: 'Revisao de contratos criticos', description: 'Auditoria de 100% contratos acima de R$500k', status: 'PENDENTE', priority: 'P2', responsible: 'Ricardo Souza', assigned_to: 'user-11', start_date: '2026-05-01', due_date: '2026-08-31', completed_at: null, progress: 0, evidence_required: true, notes: null, cost_estimate: 20000, cost_actual: 0, cost_type: 'OPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: 'FIN-AUT-10', plan_id: 'plan-fin-2026', pillar_id: 'pillar-1', area_okr_id: 'area-okr-fin-1', initiative_id: 'init-9', parent_action_id: null, pack_id: 'pack-fin-2026', program_key: 'automacao', objective_key: 'F4', section_id: null, node_type: 'acao', title: 'Painel de indicadores financeiros', description: 'BI consolidado para C-Level', status: 'EM_ANDAMENTO', priority: 'P0', responsible: 'Maria Santos', assigned_to: 'user-5', start_date: '2026-01-20', due_date: '2026-04-30', completed_at: null, progress: 55, evidence_required: true, notes: 'Indicadores basicos no painel', cost_estimate: 35000, cost_actual: 19000, cost_type: 'CAPEX', currency: 'BRL', created_at: '2026-01-20T00:00:00Z', updated_at: '2026-03-15T00:00:00Z' },
]

// ============================================================
// SUBTAREFAS
// ============================================================

mockStore.subtasks = [
  { id: 'subtask-1', action_id: 'RH-DES-03', title: 'Definir trilhas por nível de liderança', completed: true, completed_at: '2026-02-15T00:00:00Z', sort_order: 1 },
  { id: 'subtask-2', action_id: 'RH-DES-03', title: 'Mapear líderes elegíveis', completed: true, completed_at: '2026-02-20T00:00:00Z', sort_order: 2 },
  { id: 'subtask-3', action_id: 'RH-DES-03', title: 'Publicar calendário anual', completed: false, completed_at: null, sort_order: 3 },
  { id: 'subtask-4', action_id: 'RH-DES-03', title: 'Executar 1º módulo', completed: false, completed_at: null, sort_order: 4 },
  { id: 'subtask-5', action_id: 'RH-CON-01', title: 'Definir critério de decisão relevante', completed: false, completed_at: null, sort_order: 1 },
  { id: 'subtask-6', action_id: 'RH-CON-01', title: 'Publicar template + repositório', completed: false, completed_at: null, sort_order: 2 },
  { id: 'subtask-7', action_id: 'OPS-RPA-01', title: 'Mapear processos candidatos', completed: true, completed_at: '2026-01-25T00:00:00Z', sort_order: 1 },
  { id: 'subtask-8', action_id: 'OPS-RPA-01', title: 'Priorizar por ROI', completed: true, completed_at: '2026-01-30T00:00:00Z', sort_order: 2 },
  { id: 'subtask-9', action_id: 'OPS-RPA-01', title: 'Desenvolver bots P0', completed: true, completed_at: '2026-02-20T00:00:00Z', sort_order: 3 },
  { id: 'subtask-10', action_id: 'OPS-RPA-01', title: 'Testar em homologação', completed: true, completed_at: '2026-02-28T00:00:00Z', sort_order: 4 },
  { id: 'subtask-11', action_id: 'OPS-RPA-01', title: 'Deploy Fase 1', completed: true, completed_at: '2026-03-10T00:00:00Z', sort_order: 5 },
  { id: 'subtask-12', action_id: 'OPS-RPA-01', title: 'Deploy Fase 2', completed: false, completed_at: null, sort_order: 6 },
  { id: 'subtask-13', action_id: 'action-ti-1', title: 'Assessment de infraestrutura', completed: true, completed_at: '2026-01-20T00:00:00Z', sort_order: 1 },
  { id: 'subtask-14', action_id: 'action-ti-1', title: 'Definir arquitetura cloud', completed: true, completed_at: '2026-02-01T00:00:00Z', sort_order: 2 },
  { id: 'subtask-15', action_id: 'action-ti-1', title: 'Migrar módulo financeiro', completed: true, completed_at: '2026-02-28T00:00:00Z', sort_order: 3 },
  { id: 'subtask-16', action_id: 'action-ti-1', title: 'Migrar módulo de RH', completed: false, completed_at: null, sort_order: 4 },
  { id: 'subtask-17', action_id: 'action-ti-1', title: 'Migrar módulo de vendas', completed: false, completed_at: null, sort_order: 5 },
  { id: 'subtask-18', action_id: 'MKT-INB-01', title: 'Definir personas', completed: true, completed_at: '2026-01-15T00:00:00Z', sort_order: 1 },
  { id: 'subtask-19', action_id: 'MKT-INB-01', title: 'Criar calendário editorial', completed: true, completed_at: '2026-01-20T00:00:00Z', sort_order: 2 },
  { id: 'subtask-20', action_id: 'MKT-INB-01', title: 'Configurar automação', completed: false, completed_at: null, sort_order: 3 },
]

// ============================================================
// EVIDÊNCIAS
// ============================================================

mockStore.evidences = [
  { id: 'evidence-1', action_id: 'RH-CON-01', filename: 'template_log_decisoes_v1.pdf', storage_path: '/evidences/rh/template_log_decisoes_v1.pdf', file_size: 1200000, mime_type: 'application/pdf', submitted_by: 'user-1', submitted_at: '2026-02-20T00:00:00Z', status: 'PENDENTE' },
  { id: 'evidence-2', action_id: 'OPS-RPA-02', filename: 'vsm_cadeia_suprimentos.pdf', storage_path: '/evidences/ops/vsm_cadeia_suprimentos.pdf', file_size: 5200000, mime_type: 'application/pdf', submitted_by: 'user-3', submitted_at: '2026-02-21T00:00:00Z', status: 'APROVADA' },
  { id: 'evidence-3', action_id: 'action-ti-3', filename: 'relatorio_upgrade_rede.pdf', storage_path: '/evidences/ti/relatorio_upgrade_rede.pdf', file_size: 3100000, mime_type: 'application/pdf', submitted_by: 'user-4', submitted_at: '2026-03-16T00:00:00Z', status: 'APROVADA' },
  { id: 'evidence-4', action_id: 'MKT-BRD-02', filename: 'site_launch_report.pdf', storage_path: '/evidences/mkt/site_launch_report.pdf', file_size: 1800000, mime_type: 'application/pdf', submitted_by: 'user-8', submitted_at: '2026-02-21T00:00:00Z', status: 'APROVADA' },
  { id: 'evidence-5', action_id: 'FIN-COM-01', filename: 'grc_implementation.pdf', storage_path: '/evidences/fin/grc_implementation.pdf', file_size: 4200000, mime_type: 'application/pdf', submitted_by: 'user-11', submitted_at: '2026-01-29T00:00:00Z', status: 'APROVADA' },
  { id: 'evidence-6', action_id: 'RH-INO-04', filename: 'painel_rh_v1_screenshot.png', storage_path: '/evidences/rh/painel_rh_v1_screenshot.png', file_size: 890000, mime_type: 'image/png', submitted_by: 'user-6', submitted_at: '2026-03-16T00:00:00Z', status: 'PENDENTE' },
  { id: 'evidence-7', action_id: 'action-ti-2', filename: 'zero_trust_audit.pdf', storage_path: '/evidences/ti/zero_trust_audit.pdf', file_size: 2900000, mime_type: 'application/pdf', submitted_by: 'user-10', submitted_at: '2026-03-21T00:00:00Z', status: 'APROVADA_GESTOR' },
  { id: 'evidence-8', action_id: 'OPS-LEA-02', filename: 'dashboards_producao.xlsx', storage_path: '/evidences/ops/dashboards_producao.xlsx', file_size: 1500000, mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', submitted_by: 'user-9', submitted_at: '2026-03-26T00:00:00Z', status: 'PENDENTE' },
]

// ============================================================
// COMENTÁRIOS
// ============================================================

mockStore.comments = [
  { id: 'comment-1', action_id: 'RH-DES-01', content: 'Checklist 4/4 definido, falta validar com líderes.', user_id: 'user-1', created_at: '2026-02-15T10:00:00Z', updated_at: '2026-02-15T10:00:00Z', user_email: 'renata.silvestre@empresa.com', user_role: 'gestor' },
  { id: 'comment-2', action_id: 'RH-DES-01', content: 'Precisamos travar baseline antes de 15/mar.', user_id: 'manager-1', created_at: '2026-02-20T14:30:00Z', updated_at: '2026-02-20T14:30:00Z', user_email: 'gestor.rh@empresa.com', user_role: 'direcao' },
  { id: 'comment-3', action_id: 'OPS-RPA-01', content: 'ROI dos primeiros bots já está positivo!', user_id: 'user-3', created_at: '2026-03-05T09:00:00Z', updated_at: '2026-03-05T09:00:00Z', user_email: 'roberto.lima@empresa.com', user_role: 'gestor' },
  { id: 'comment-4', action_id: 'action-ti-1', content: 'Migração do módulo financeiro concluída sem downtime.', user_id: 'user-4', created_at: '2026-03-01T16:00:00Z', updated_at: '2026-03-01T16:00:00Z', user_email: 'carlos.mendes@empresa.com', user_role: 'gestor' },
  { id: 'comment-5', action_id: 'RH-INO-03', content: 'Dicionário de KPIs em revisão com Produto/Dados.', user_id: 'user-6', created_at: '2026-03-22T11:00:00Z', updated_at: '2026-03-22T11:00:00Z', user_email: 'fernanda.xavier@empresa.com', user_role: 'colaborador' },
]

// ============================================================
// HISTÓRICO
// ============================================================

mockStore.history = [
  { id: 'history-1', action_id: 'RH-CON-01', field_changed: 'status', old_value: 'PENDENTE', new_value: 'PENDENTE', changed_by: 'user-1', changed_at: '2026-02-06T08:00:00Z' },
  { id: 'history-2', action_id: 'RH-DES-01', field_changed: 'status', old_value: 'PENDENTE', new_value: 'PENDENTE', changed_by: 'user-1', changed_at: '2026-02-06T10:00:00Z' },
  { id: 'history-3', action_id: 'RH-INO-01', field_changed: 'status', old_value: 'PENDENTE', new_value: 'PENDENTE', changed_by: 'user-1', changed_at: '2026-02-06T15:00:00Z' },
  { id: 'history-4', action_id: 'RH-DES-07', field_changed: 'status', old_value: 'PENDENTE', new_value: 'PENDENTE', changed_by: 'user-1', changed_at: '2026-02-15T17:00:00Z' },
  { id: 'history-5', action_id: 'OPS-RPA-02', field_changed: 'status', old_value: 'EM_ANDAMENTO', new_value: 'CONCLUIDA', changed_by: 'user-3', changed_at: '2026-02-20T16:00:00Z' },
  { id: 'history-6', action_id: 'action-ti-3', field_changed: 'status', old_value: 'EM_ANDAMENTO', new_value: 'CONCLUIDA', changed_by: 'user-4', changed_at: '2026-03-15T18:00:00Z' },
  { id: 'history-7', action_id: 'RH-INO-03', field_changed: 'status', old_value: 'PENDENTE', new_value: 'PENDENTE', changed_by: 'user-6', changed_at: '2026-03-20T09:00:00Z' },
]

// ============================================================
// RISCOS
// ============================================================

mockStore.risks = [
  { id: 'risk-1', action_id: 'RH-DES-03', risk_label: 'Baixa adesão dos líderes na Escola', risk_level: 'MEDIO', mitigation: 'Comunicação intensiva e envolvimento da Direção' },
  { id: 'risk-2', action_id: 'action-ti-1', risk_label: 'Downtime durante migração', risk_level: 'ALTO', mitigation: 'Migração em horário de baixo uso e rollback plan' },
  { id: 'risk-3', action_id: 'action-ti-1', risk_label: 'Atraso por complexidade técnica', risk_level: 'MEDIO', mitigation: 'Buffer de tempo e consultoria especializada' },
  { id: 'risk-4', action_id: 'OPS-RPA-01', risk_label: 'Resistência à mudança', risk_level: 'MEDIO', mitigation: 'Change management e treinamento' },
  { id: 'risk-5', action_id: 'FIN-AUT-01', risk_label: 'Integração com sistemas legados', risk_level: 'ALTO', mitigation: 'POC antes do desenvolvimento completo' },
  { id: 'risk-6', action_id: 'MKT-INB-01', risk_label: 'Baixa conversão inicial', risk_level: 'BAIXO', mitigation: 'Testes A/B e otimização contínua' },
]

// Export para uso
export const mockActions = mockStore.actions
export const mockSubtasks = mockStore.subtasks
export const mockEvidences = mockStore.evidences
export const mockComments = mockStore.comments
export const mockHistory = mockStore.history
export const mockRisks = mockStore.risks
