export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  GOALS: '/goals',
  INDICATORS: '/indicators',
  ACTION_PLANS: '/action-plans',
  ACTION_PLANS_DASHBOARD: '/action-plans/dashboard',
  ACTION_PLANS_KANBAN: '/action-plans/kanban',
  ACTION_PLANS_TIMELINE: '/action-plans/timeline',
  ACTION_PLANS_CALENDAR: '/action-plans/calendar',
  ACTION_PLANS_RISKS: '/action-plans/risks',
  INITIATIVES: '/initiatives',
  ADMIN: '/admin',
  CALENDAR: '/calendar',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  CAPACITY: '/capacity',
  FINANCE: '/finance',
  AREAS: '/areas',
  GOVERNANCE_DECISIONS: '/governance/decisions',
  GOVERNANCE_RISKS: '/governance/risks',
  GOVERNANCE_EVIDENCES: '/governance/evidences',
  GOVERNANCE_TRACEABILITY: '/governance/traceability',
  GOVERNANCE_COMMITTEES: '/governance/committees',
  GOVERNANCE_CLOSINGS: '/governance/closings',
  GOVERNANCE_CLOSINGS_DETAIL: '/governance/closings/:id',
  GOVERNANCE_CLOSINGS_COMPARE: '/governance/closings/compare',
  STRATEGY: '/strategy',
  STRATEGY_OVERVIEW: '/strategy',
  STRATEGY_THESIS: '/strategy/thesis',
  STRATEGY_PILLARS: '/strategy/pillars',
  STRATEGY_OKRS: '/strategy/okrs',
  STRATEGY_KPIS: '/strategy/kpis',
  STRATEGY_SCENARIOS: '/strategy/scenarios',
  STRATEGY_RISKS: '/strategy/risks',
  MONETIZATION: '/monetization',
  AREA_PLANS: '/area-plans',
  AREA_PLAN_DETAIL: '/area-plans/:areaSlug',
  AREA_PLAN_KANBAN: '/area-plans/:areaSlug/kanban',
  AREA_PLAN_TIMELINE: '/area-plans/:areaSlug/timeline',
  AREA_PLAN_APPROVALS: '/area-plans/:areaSlug/approvals',

  // Módulo Planejamento (novo)
  PLANNING: '/planning',
  PLANNING_DASHBOARD: '/planning/dashboard',
  PLANNING_KANBAN: '/planning/kanban',
  PLANNING_CALENDAR: '/planning/calendar',
  PLANNING_TIMELINE: '/planning/timeline',
  PLANNING_ACTIONS: '/planning/actions',
  PLANNING_ACTIONS_NEW: '/planning/actions/new',
  PLANNING_ACTIONS_MANAGE: '/planning/actions/manage',
  PLANNING_ACTIONS_TEMPLATES: '/planning/actions/templates',
  PLANNING_ACTIONS_APPROVALS: '/planning/actions/approvals',
  PLANNING_ACTIONS_EVIDENCES: '/planning/actions/evidences',
  PLANNING_AREA: '/planning/:areaSlug',
  PLANNING_AREA_DASHBOARD: '/planning/:areaSlug/dashboard',
  PLANNING_AREA_KANBAN: '/planning/:areaSlug/kanban',
  PLANNING_AREA_CALENDAR: '/planning/:areaSlug/calendar',
  PLANNING_AREA_TIMELINE: '/planning/:areaSlug/timeline',
  PLANNING_AREA_STRATEGIC_PACK: '/planning/:areaSlug/pe-2026',
  ADMIN_OKRS: '/admin/okrs',
  ADMIN_PILLARS: '/admin/pillars',
  ADMIN_AREAS: '/admin/areas',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_INTEGRATIONS: '/admin/integrations',
  ADMIN_CONTEXTS: '/admin/contexts',
  ADMIN_MIGRATION: '/admin/migration',
  ADMIN_TEMPLATES: '/admin/templates',
  ADMIN_VALIDATION: '/admin/validation',

  // Cockpit expandido
  ALERTS: '/alerts',
  CUSTOM_DASHBOARDS: '/dashboards',

  // Inteligência & Analytics
  ANALYTICS: '/analytics',
  ANALYTICS_SCOREBOARD: '/analytics/scoreboard',
  ANALYTICS_INSIGHTS: '/analytics/insights',
  ANALYTICS_DASHBOARDS: '/analytics/dashboards',
  ANALYTICS_BENCHMARK: '/analytics/benchmark',
  ANALYTICS_FORECASTS: '/analytics/forecasts',
  ANALYTICS_DATA_HEALTH: '/analytics/data-health',

  // Controle & Auditoria
  AUDIT: '/audit',
  AUDIT_LOGS: '/audit/logs',
  AUDIT_COMPLIANCE: '/audit/compliance',
  AUDIT_ACCESS: '/audit/access',
  AUDIT_EVIDENCES: '/audit/evidences',
  AUDIT_RISK_MAP: '/audit/risk-map',
} as const

export type RouteKey = keyof typeof ROUTES
